steps:
  # Step 1: Install npm dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install'] 
    id: 'Install Dependencies'

  # Step 2: Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    id: 'Build Application'

  # Step 3: Deploy to Cloud Run using gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deegallery-api' 
      - '--source'
      - '.' 
      - '--region'
      - 'asia-south1' 
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - '${PROJECT_ID}'
      # Securely link the service to secrets in Secret Manager
      - '--update-secrets=DATABASE_URL=deeluvgallery-db-url:latest,SESSION_SECRET=deeluvgallery-session-secret:latest'
      - '--set-env-vars=NODE_ENV=production'
    id: 'Deploy to Cloud Run'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'