steps:
  # Step 1: Install all project dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    id: 'Install Dependencies'

  # Step 2: Build the server code using the script from package.json
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:server']
    id: 'Build Server'
  
  # Step 3: Run database migrations as a dedicated build step
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Run Database Migrations'
    entrypoint: 'npm'
    args: ['run', 'db:migrate']
    secretEnv: ['DATABASE_URL']

  # Step 4: Deploy to Cloud Run only after migrations are successful
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'deegallery-api'
      - '--source'
      - '.'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - '${PROJECT_ID}'
      - '--update-secrets=DATABASE_URL=deeluvgallery-db-url:latest,SESSION_SECRET=deeluvgallery-session-secret:latest'
      - '--set-env-vars=NODE_ENV=production'

# This section makes secrets available to the build steps
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/deeluvgallery-db-url/versions/latest
    env: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'