[build]
  base = "."
  publish = "client/dist"
  command = "npm install && npm run build:client"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://dee-inc-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/photos/*"
  to = "https://dee-inc-api.onrender.com/photos/:splat"
  status = 200

[[redirects]]
  from = "/moments/*"
  to = "https://dee-inc-api.onrender.com/moments/:splat"
  status = 200