[build]
  base = "."
  publish = "dist/public"
  command = "npm install && npm run build:client"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://deegallery-api-155894580321.asia-south1.run.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/photos/*"
  to = "https://deegallery-api-155894580321.asia-south1.run.app/photos/:splat"
  status = 200

[[redirects]]
  from = "/moments/*"
  to = "https://deegallery-api-155894580321.asia-south1.run.app/moments/:splat"
  status = 200