services:
  - type: web
    name: photo-gallery-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: photo-gallery-db
          property: connectionString
    autoDeploy: false

databases:
  - name: photo-gallery-db
    databaseName: photogallery
    user: photogallery
    plan: starter